"""One-off importer: reads the legacy presets.ts and the review decisions below,
writes src/catalog.ts. Re-run only if the review decisions change."""
import re, json, pathlib
root = pathlib.Path(__file__).resolve().parents[3]
src = (root / "frontend/src/lib/presets.ts").read_text()
rows = re.findall(r'\{ id: "(q\d+)", prompt: "((?:[^"\\]|\\.)*)", options: \[(.*?)\], tags: \[(.*?)\] \}', src)
assert len(rows) == 210, len(rows)

EXCLUDED = {
  "q123": "names real people as 'worst' — personal callout, politically loaded",
  "q129": "platform politics — excluded topic",
  "q135": "podcast list is politically loaded — excluded topic",
}
RETIRED = {
  "q187": "duplicate of q075 (wedding song)",
  "q147": "overlaps q144 (childhood show); keep the broader one",
}
SPOILER = {
  "q029": "villain list reveals a betrayal twist (Bleach)",
  "q033": "discusses an ending (Attack on Titan)",
  "q036": "fight list reveals late-series events (JJK)",
  "q037": "options are character deaths / endings",
  "q059": "naming a film as having a twist is itself a spoiler",
  "q199": "options are series endings",
}
# Substantive edits create version 2; the original version stays as history.
EDITS = {
  "q199": {"prompt": "Worst TV series ending?", "options": ["Game of Thrones", "How I Met Your Mother", "Lost", "Dexter"], "note": "prompt said 'movie' but every option is a TV series"},
  "q200": {"prompt": "Best modern animated show?", "options": ["Arcane", "Bluey", "Invincible", "Bob's Burgers"], "note": "'Spider-Verse vibes' was not a show; replaced with a real option"},
  "q082": {"prompt": "Cereal: milk or cereal first?", "options": ["Cereal first", "Milk first", "I don't eat cereal"], "note": "dropped the 'sociopath' jab from an option"},
}
TOPICS = {"gaming","anime","sports","movies","music","food","tech","internet","school","nostalgia"}

out = []
for qid, prompt, opts, tags in rows:
    options = re.findall(r'"((?:[^"\\]|\\.)*)"', opts)
    tag_list = re.findall(r'"([^"]+)"', tags)
    prompt = prompt.replace('\\"', '"')
    options = [o.replace('\\"', '"') for o in options]
    topic = next((t for t in tag_list if t in TOPICS), None)
    versions = []
    v1 = {"version": 1, "prompt": prompt, "options": options}
    versions.append(v1)
    if qid in EDITS:
        e = EDITS[qid]
        versions.append({"version": 2, "prompt": e["prompt"], "options": e["options"], "note": e["note"]})
    if qid in EXCLUDED:
        status, note = "excluded", EXCLUDED[qid]
    elif qid in RETIRED:
        status, note = "retired", RETIRED[qid]
    else:
        status, note = "approved", None
    out.append({
        "id": qid, "tags": tag_list, "topic": topic,
        "spoiler": qid in SPOILER, "spoilerNote": SPOILER.get(qid),
        "status": status, "note": note, "versions": versions,
    })

lines = ["// GENERATED by scripts/import-presets.py from the legacy presets library.",
         "// Stable ids (q###) match frontend/src/lib/presets.ts. Substantive edits add a version;",
         "// the latest version is the active one. Do not edit old versions.",
         'import type { CatalogQuestion } from "./types.ts";', "",
         "export const CATALOG: CatalogQuestion[] = ["]
for q in out:
    vs = []
    for v in q["versions"]:
        opts = ", ".join(json.dumps({"id": f"o{i+1}", "text": t}) for i, t in enumerate(v["options"]))
        note = f', note: {json.dumps(v["note"])}' if v.get("note") else ""
        vs.append(f'{{ version: {v["version"]}, prompt: {json.dumps(v["prompt"])}, options: [{opts}]{note} }}')
    sp = f', spoilerNote: {json.dumps(q["spoilerNote"])}' if q["spoilerNote"] else ""
    nt = f', note: {json.dumps(q["note"])}' if q["note"] else ""
    lines.append(f'  {{ id: {json.dumps(q["id"])}, topic: {json.dumps(q["topic"])}, tags: {json.dumps(q["tags"])}, spoiler: {str(q["spoiler"]).lower()}{sp}, status: {json.dumps(q["status"])}{nt},')
    lines.append(f'    versions: [{", ".join(vs)}] }},')
lines.append("];")
(root / "packages/content/src/catalog.ts").write_text("\n".join(lines) + "\n")
print("wrote", len(out), "questions;", sum(1 for q in out if q["status"]=="approved"), "approved")
