// Entry point for the public SvelteKit Worker (wrangler.toml `main`).
//
// /api/* (HTTP and WebSocket upgrades) is forwarded to the API Worker over a
// service binding before SvelteKit ever sees the request. Keeping the API
// outside SvelteKit's request pipeline avoids header/body rewriting on 101
// upgrade responses and keeps a single origin for cookies.
//
// The SvelteKit worker itself is generated by @sveltejs/adapter-cloudflare into
// .svelte-kit/cloudflare/_worker.js (see wrangler.build.toml). Do not point the
// adapter's `main` at this file: it would overwrite it.
import sveltekit from './.svelte-kit/cloudflare/_worker.js';

interface Env {
	API: Fetcher;
	ASSETS: Fetcher;
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);
		if (url.pathname === '/api' || url.pathname.startsWith('/api/')) {
			return env.API.fetch(request);
		}
		return (sveltekit as { fetch(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> }).fetch(request, env, ctx);
	}
} satisfies ExportedHandler<Env>;
