// Settle It — Preset question library
// Each question has a stable id (q### sequential), prompt, 2-4 options, and 1-3 tags.
// Tags fall into two groups:
//   Topics:  gaming, anime, sports, movies, music, food, tech, internet, school, nostalgia
//   Vibes:   hot-take, wholesome, weird, dark-humor, friendship, hypothetical
// Most questions pair one topic + one vibe; some pure-hypotheticals use only the vibe.

export interface PresetQuestion {
  id: string;
  prompt: string;
  options: string[];
  tags: string[];
}

export const TOPIC_TAGS = ["gaming", "anime", "sports", "movies", "music", "food", "tech", "internet", "school", "nostalgia"] as const;
export const VIBE_TAGS = ["hot-take", "wholesome", "weird", "dark-humor", "friendship", "hypothetical"] as const;
export const ALL_TAGS = [...TOPIC_TAGS, ...VIBE_TAGS] as const;
export type Tag = typeof ALL_TAGS[number];

export const presets: PresetQuestion[] = [
  // ===== GAMING =====
  { id: "q001", prompt: "GOAT of competitive FPS?", options: ["Shroud", "TenZ", "s1mple", "Bugha"], tags: ["gaming", "hot-take"] },
  { id: "q002", prompt: "Best Pokemon starter of all time?", options: ["Charmander", "Bulbasaur", "Squirtle"], tags: ["gaming", "nostalgia"] },
  { id: "q003", prompt: "Hardest FromSoft game?", options: ["Sekiro", "Elden Ring", "Bloodborne", "Dark Souls 3"], tags: ["gaming", "hot-take"] },
  { id: "q004", prompt: "Most overrated game of the last decade?", options: ["GTA V", "Fortnite", "Skyrim", "Minecraft"], tags: ["gaming", "hot-take"] },
  { id: "q005", prompt: "Best Mario game ever?", options: ["Odyssey", "Galaxy", "64", "Sunshine"], tags: ["gaming", "nostalgia"] },
  { id: "q006", prompt: "Best Zelda game?", options: ["BOTW", "Ocarina of Time", "TOTK", "Majora's Mask"], tags: ["gaming", "hot-take"] },
  { id: "q007", prompt: "Mario Kart main?", options: ["Yoshi", "Toad", "Bowser", "Princess Peach"], tags: ["gaming", "nostalgia"] },
  { id: "q008", prompt: "Best Smash Bros character?", options: ["Kirby", "Fox", "Pikachu", "Sephiroth"], tags: ["gaming"] },
  { id: "q009", prompt: "Best Call of Duty?", options: ["MW2 (2009)", "Black Ops 1", "WaW", "MW2019"], tags: ["gaming", "nostalgia"] },
  { id: "q010", prompt: "Best Halo?", options: ["Halo 3", "CE", "Reach", "Halo 2"], tags: ["gaming", "nostalgia"] },
  { id: "q011", prompt: "Best video game soundtrack?", options: ["Skyrim", "Hollow Knight", "Undertale", "FFVII"], tags: ["gaming", "music"] },
  { id: "q012", prompt: "Battle royale you actually like?", options: ["Apex", "Warzone", "Fortnite", "PUBG"], tags: ["gaming", "hot-take"] },
  { id: "q013", prompt: "Minecraft or Roblox as a kid?", options: ["Minecraft", "Roblox", "Both", "Neither"], tags: ["gaming", "nostalgia"] },
  { id: "q014", prompt: "Best villain in gaming?", options: ["Handsome Jack", "GLaDOS", "Sephiroth", "Bowser"], tags: ["gaming"] },
  { id: "q015", prompt: "PC or Console?", options: ["PC", "Console", "Both equally"], tags: ["gaming", "hot-take"] },
  { id: "q016", prompt: "Open world or linear?", options: ["Open world", "Linear", "Depends"], tags: ["gaming", "hot-take"] },
  { id: "q017", prompt: "Best fighting game?", options: ["Street Fighter", "Tekken", "Smash", "Mortal Kombat"], tags: ["gaming"] },
  { id: "q018", prompt: "Most influential game ever?", options: ["Super Mario Bros", "Doom", "Minecraft", "WoW"], tags: ["gaming", "hot-take"] },
  { id: "q019", prompt: "Best Nintendo console?", options: ["Switch", "Wii", "N64", "GameCube"], tags: ["gaming", "nostalgia"] },
  { id: "q020", prompt: "MMO that actually mattered?", options: ["WoW", "RuneScape", "FFXIV", "OSRS"], tags: ["gaming"] },
  { id: "q021", prompt: "Best indie game of all time?", options: ["Hollow Knight", "Hades", "Celeste", "Stardew Valley"], tags: ["gaming"] },
  { id: "q022", prompt: "Most replayable game?", options: ["Skyrim", "Minecraft", "Civ VI", "Stardew"], tags: ["gaming"] },
  { id: "q023", prompt: "Hardest boss you've ever beaten?", options: ["Malenia", "Sister Friede", "Isshin", "Radahn"], tags: ["gaming"] },
  { id: "q024", prompt: "Best Pokemon generation?", options: ["Gen 1", "Gen 2", "Gen 3", "Gen 4"], tags: ["gaming", "nostalgia"] },
  { id: "q025", prompt: "Worst gaming controversy?", options: ["Loot boxes", "Cyberpunk launch", "Battlefront 2", "NFTs in games"], tags: ["gaming", "hot-take"] },

  // ===== ANIME =====
  { id: "q026", prompt: "Best shounen of all time?", options: ["One Piece", "Naruto", "Bleach", "HxH"], tags: ["anime", "hot-take"] },
  { id: "q027", prompt: "Subbed or dubbed?", options: ["Subbed", "Dubbed", "Depends on show"], tags: ["anime", "hot-take"] },
  { id: "q028", prompt: "Best anime studio?", options: ["MAPPA", "Ufotable", "Studio Ghibli", "Bones"], tags: ["anime"] },
  { id: "q029", prompt: "Best anime villain?", options: ["Aizen", "Light Yagami", "Madara", "Father (FMA)"], tags: ["anime"] },
  { id: "q030", prompt: "Best anime opening song?", options: ["Tank! (Cowboy Bebop)", "Guren no Yumiya", "Cha-La Head-Cha-La", "Unravel"], tags: ["anime", "music"] },
  { id: "q031", prompt: "Most overrated anime?", options: ["Naruto", "AOT", "Death Note", "DBZ"], tags: ["anime", "hot-take"] },
  { id: "q032", prompt: "Best Studio Ghibli film?", options: ["Spirited Away", "Mononoke", "Howl's Moving Castle", "Totoro"], tags: ["anime", "movies"] },
  { id: "q033", prompt: "Did AOT stick the landing?", options: ["Yes", "No", "Mostly"], tags: ["anime", "hot-take"] },
  { id: "q034", prompt: "Best slice-of-life anime?", options: ["K-On!", "Yuru Camp", "Bunny Girl Senpai", "Welcome to NHK"], tags: ["anime", "wholesome"] },
  { id: "q035", prompt: "Best anime mecha?", options: ["EVA-01", "Gurren Lagann", "Gundam Wing", "Optimus (close enough)"], tags: ["anime"] },
  { id: "q036", prompt: "Best anime fight?", options: ["Gojo vs Sukuna", "Naruto vs Sasuke", "Goku vs Frieza", "Luffy vs Lucci"], tags: ["anime"] },
  { id: "q037", prompt: "Saddest anime moment?", options: ["Nina (FMA)", "Jiraiya's death", "Maes Hughes", "Your Name ending"], tags: ["anime", "dark-humor"] },
  { id: "q038", prompt: "Filler arc that's actually worth it?", options: ["Land of Waves", "Bount Arc", "Skypiea", "None"], tags: ["anime"] },
  { id: "q039", prompt: "Best isekai?", options: ["Re:Zero", "Konosuba", "Mushoku Tensei", "That Time I Got Reincarnated"], tags: ["anime"] },
  { id: "q040", prompt: "Most underrated anime?", options: ["Mushishi", "Monster", "March Comes In Like A Lion", "Vinland Saga"], tags: ["anime", "hot-take"] },
  { id: "q041", prompt: "Best romance anime?", options: ["Toradora", "Your Lie in April", "Fruits Basket", "Horimiya"], tags: ["anime", "wholesome"] },
  { id: "q042", prompt: "First anime you ever watched?", options: ["Naruto", "DBZ", "Pokemon", "Yu-Gi-Oh!"], tags: ["anime", "nostalgia"] },
  { id: "q043", prompt: "Best anime protagonist?", options: ["Luffy", "Goku", "Edward Elric", "Saitama"], tags: ["anime"] },

  // ===== MOVIES =====
  { id: "q044", prompt: "Best Marvel movie?", options: ["Endgame", "Infinity War", "GotG", "Winter Soldier"], tags: ["movies", "hot-take"] },
  { id: "q045", prompt: "Best Pixar movie?", options: ["Inside Out", "Toy Story 3", "Wall-E", "Ratatouille"], tags: ["movies", "wholesome"] },
  { id: "q046", prompt: "Best Christmas movie?", options: ["Home Alone", "Elf", "Die Hard", "The Polar Express"], tags: ["movies", "nostalgia"] },
  { id: "q047", prompt: "Scariest movie ever?", options: ["The Exorcist", "Hereditary", "The Shining", "Sinister"], tags: ["movies", "dark-humor"] },
  { id: "q048", prompt: "Best Christopher Nolan movie?", options: ["Inception", "Interstellar", "Dark Knight", "Memento"], tags: ["movies", "hot-take"] },
  { id: "q049", prompt: "Best Tarantino movie?", options: ["Pulp Fiction", "Kill Bill", "Inglourious Basterds", "Reservoir Dogs"], tags: ["movies"] },
  { id: "q050", prompt: "Most rewatchable movie?", options: ["The Departed", "LOTR", "Shrek", "Back to the Future"], tags: ["movies"] },
  { id: "q051", prompt: "Best trilogy?", options: ["LOTR", "OG Star Wars", "Dark Knight", "Toy Story"], tags: ["movies"] },
  { id: "q052", prompt: "Worst sequel ever?", options: ["Matrix Resurrections", "Star Wars: Rise of Skywalker", "Indiana Jones 4", "Speed 2"], tags: ["movies", "hot-take"] },
  { id: "q053", prompt: "Best A24 film?", options: ["Everything Everywhere", "Hereditary", "Lady Bird", "Moonlight"], tags: ["movies"] },
  { id: "q054", prompt: "Most overrated movie of all time?", options: ["Avatar", "Titanic", "Forrest Gump", "Citizen Kane"], tags: ["movies", "hot-take"] },
  { id: "q055", prompt: "Best Bond actor?", options: ["Sean Connery", "Daniel Craig", "Pierce Brosnan", "Roger Moore"], tags: ["movies"] },
  { id: "q056", prompt: "Best superhero movie ever?", options: ["Dark Knight", "Logan", "Into the Spider-Verse", "Infinity War"], tags: ["movies"] },
  { id: "q057", prompt: "Best DreamWorks film?", options: ["Shrek", "How to Train Your Dragon", "Kung Fu Panda", "Madagascar"], tags: ["movies", "nostalgia"] },
  { id: "q058", prompt: "Most quotable movie?", options: ["Anchorman", "Mean Girls", "The Big Lebowski", "Princess Bride"], tags: ["movies"] },
  { id: "q059", prompt: "Best plot twist in film?", options: ["Sixth Sense", "Fight Club", "Usual Suspects", "Empire Strikes Back"], tags: ["movies"] },
  { id: "q060", prompt: "Best horror movie of last 10 years?", options: ["Hereditary", "Get Out", "The Witch", "Talk to Me"], tags: ["movies", "dark-humor"] },
  { id: "q061", prompt: "Best comedy of the 2000s?", options: ["Superbad", "Anchorman", "Step Brothers", "The Hangover"], tags: ["movies", "nostalgia"] },
  { id: "q062", prompt: "Movie that everyone loves but you don't?", options: ["Avatar", "La La Land", "Joker", "Whiplash"], tags: ["movies", "hot-take"] },
  { id: "q063", prompt: "Best animated movie that isn't Pixar or Ghibli?", options: ["Spider-Verse", "Klaus", "Prince of Egypt", "Lion King"], tags: ["movies"] },

  // ===== MUSIC =====
  { id: "q064", prompt: "Best Kendrick album?", options: ["GKMC", "TPAB", "DAMN.", "Mr. Morale"], tags: ["music", "hot-take"] },
  { id: "q065", prompt: "GOAT rapper?", options: ["Kendrick", "Eminem", "Jay-Z", "Nas"], tags: ["music", "hot-take"] },
  { id: "q066", prompt: "Best decade for music?", options: ["70s", "80s", "90s", "2000s"], tags: ["music", "hot-take"] },
  { id: "q067", prompt: "Best Drake song?", options: ["Marvin's Room", "Started From the Bottom", "Hotline Bling", "Passionfruit"], tags: ["music"] },
  { id: "q068", prompt: "Best Beatles album?", options: ["Abbey Road", "Sgt. Pepper's", "Revolver", "White Album"], tags: ["music"] },
  { id: "q069", prompt: "Most overrated artist?", options: ["Taylor Swift", "Drake", "Kanye", "Beyoncé"], tags: ["music", "hot-take"] },
  { id: "q070", prompt: "Concert worth selling a kidney for?", options: ["Beyoncé", "Taylor Swift", "Kendrick", "Tyler, the Creator"], tags: ["music"] },
  { id: "q071", prompt: "Best song to drive to at 2am?", options: ["Marvin's Room", "Redbone", "Pyramids", "Nights"], tags: ["music"] },
  { id: "q072", prompt: "Best workout song?", options: ["Till I Collapse", "Stronger", "POWER", "X Gon' Give It"], tags: ["music"] },
  { id: "q073", prompt: "Best Tyler, the Creator album?", options: ["IGOR", "Flower Boy", "Call Me If You Get Lost", "Wolf"], tags: ["music"] },
  { id: "q074", prompt: "Best Kanye album?", options: ["MBDTF", "Graduation", "808s", "TLOP"], tags: ["music", "hot-take"] },
  { id: "q075", prompt: "Best song to play at a wedding?", options: ["September", "Sweet Caroline", "I Wanna Dance With Somebody", "Mr. Brightside"], tags: ["music", "wholesome"] },
  { id: "q076", prompt: "Guilty pleasure song?", options: ["Call Me Maybe", "Mr. Brightside", "Africa", "Wonderwall"], tags: ["music", "nostalgia"] },
  { id: "q077", prompt: "Most overplayed song?", options: ["Don't Stop Believin'", "Sweet Caroline", "Mr. Brightside", "Wonderwall"], tags: ["music", "hot-take"] },
  { id: "q078", prompt: "Best modern pop star?", options: ["Sabrina Carpenter", "Olivia Rodrigo", "Chappell Roan", "Doja Cat"], tags: ["music"] },

  // ===== FOOD =====
  { id: "q079", prompt: "Pineapple on pizza?", options: ["Yes", "No", "Only if there's ham"], tags: ["food", "hot-take"] },
  { id: "q080", prompt: "Best fast food chain?", options: ["Chick-fil-A", "In-N-Out", "Five Guys", "McDonald's"], tags: ["food", "hot-take"] },
  { id: "q081", prompt: "Is a hot dog a sandwich?", options: ["Yes", "No", "Only sometimes"], tags: ["food", "weird"] },
  { id: "q082", prompt: "Cereal: milk or cereal first?", options: ["Cereal first", "Milk first (sociopath)", "I don't eat cereal"], tags: ["food", "weird"] },
  { id: "q083", prompt: "Best pizza topping?", options: ["Pepperoni", "Mushroom", "Sausage", "Plain cheese"], tags: ["food"] },
  { id: "q084", prompt: "Ketchup on a hot dog?", options: ["Yes", "Never", "Only as a kid"], tags: ["food", "hot-take"] },
  { id: "q085", prompt: "Best comfort food?", options: ["Mac and cheese", "Ramen", "Mashed potatoes", "Grilled cheese"], tags: ["food", "wholesome"] },
  { id: "q086", prompt: "Best breakfast food?", options: ["Pancakes", "Waffles", "French toast", "Breakfast burrito"], tags: ["food"] },
  { id: "q087", prompt: "Coke or Pepsi?", options: ["Coke", "Pepsi", "Neither"], tags: ["food", "hot-take"] },
  { id: "q088", prompt: "Coffee or tea?", options: ["Coffee", "Tea", "Both", "Neither"], tags: ["food"] },
  { id: "q089", prompt: "Best Taco Bell item?", options: ["Crunchwrap", "Nachos BellGrande", "Cheesy Gordita Crunch", "Doritos Locos Taco"], tags: ["food"] },
  { id: "q090", prompt: "Most overrated food?", options: ["Avocado toast", "Truffle anything", "Caviar", "Lobster"], tags: ["food", "hot-take"] },
  { id: "q091", prompt: "Best ice cream flavor?", options: ["Mint chip", "Cookies and cream", "Chocolate chip cookie dough", "Strawberry"], tags: ["food"] },
  { id: "q092", prompt: "Best burger chain?", options: ["In-N-Out", "Shake Shack", "Five Guys", "Whataburger"], tags: ["food"] },
  { id: "q093", prompt: "Best chip flavor?", options: ["Salt and vinegar", "BBQ", "Sour cream and onion", "Plain"], tags: ["food"] },
  { id: "q094", prompt: "Crunchy or smooth peanut butter?", options: ["Crunchy", "Smooth", "Hate peanut butter"], tags: ["food", "hot-take"] },
  { id: "q095", prompt: "Best late-night snack?", options: ["Cold pizza", "Cereal", "Ramen", "Ice cream"], tags: ["food", "wholesome"] },
  { id: "q096", prompt: "Worst pizza topping?", options: ["Anchovies", "Pineapple", "Olives", "Bell peppers"], tags: ["food", "weird"] },
  { id: "q097", prompt: "Best cookie?", options: ["Chocolate chip", "Snickerdoodle", "Oatmeal raisin", "Sugar cookie"], tags: ["food"] },
  { id: "q098", prompt: "Spicy food tolerance?", options: ["I love spicy", "Medium only", "Mild please", "Plain rice tier"], tags: ["food"] },
  { id: "q099", prompt: "Best chocolate?", options: ["Milk", "Dark", "White", "Mocha"], tags: ["food", "hot-take"] },
  { id: "q100", prompt: "Worst food combination that you secretly love?", options: ["Pickles + peanut butter", "Fries in a milkshake", "Pizza dipped in ranch", "Apples with cheese"], tags: ["food", "weird"] },
  { id: "q101", prompt: "Best Chick-fil-A sauce?", options: ["Chick-fil-A sauce", "Polynesian", "Honey mustard", "BBQ"], tags: ["food"] },

  // ===== SPORTS =====
  { id: "q102", prompt: "GOAT NBA player?", options: ["MJ", "LeBron", "Kareem", "Kobe"], tags: ["sports", "hot-take"] },
  { id: "q103", prompt: "GOAT QB?", options: ["Brady", "Mahomes", "Manning", "Montana"], tags: ["sports", "hot-take"] },
  { id: "q104", prompt: "GOAT footballer (soccer)?", options: ["Messi", "Ronaldo", "Pelé", "Maradona"], tags: ["sports", "hot-take"] },
  { id: "q105", prompt: "Best sport to watch live?", options: ["Hockey", "Basketball", "Soccer", "Tennis"], tags: ["sports"] },
  { id: "q106", prompt: "Best sport to play casually?", options: ["Pickleball", "Spikeball", "Basketball", "Soccer"], tags: ["sports", "friendship"] },
  { id: "q107", prompt: "Best Olympic event?", options: ["Gymnastics", "Track 100m", "Swimming", "Diving"], tags: ["sports"] },
  { id: "q108", prompt: "Most boring sport to watch?", options: ["Baseball", "Golf", "Cricket", "NASCAR"], tags: ["sports", "hot-take"] },
  { id: "q109", prompt: "Best soccer league?", options: ["Premier League", "La Liga", "Bundesliga", "MLS (jk)"], tags: ["sports"] },
  { id: "q110", prompt: "Most overrated athlete right now?", options: ["LeBron", "Mahomes", "Curry", "Brady"], tags: ["sports", "hot-take"] },
  { id: "q111", prompt: "Best UFC fighter ever?", options: ["Jon Jones", "Khabib", "Anderson Silva", "GSP"], tags: ["sports"] },
  { id: "q112", prompt: "Trash talk: love it or hate it?", options: ["Love it", "Hate it", "Depends on athlete"], tags: ["sports", "hot-take"] },
  { id: "q113", prompt: "Best dunker of all time?", options: ["MJ", "Vince Carter", "Dr. J", "Zach LaVine"], tags: ["sports"] },

  // ===== TECH =====
  { id: "q114", prompt: "iPhone or Android?", options: ["iPhone", "Android", "I don't care"], tags: ["tech", "hot-take"] },
  { id: "q115", prompt: "Mac or PC?", options: ["Mac", "PC", "Linux"], tags: ["tech", "hot-take"] },
  { id: "q116", prompt: "Best programming language?", options: ["Python", "TypeScript", "Rust", "Go"], tags: ["tech", "hot-take"] },
  { id: "q117", prompt: "AI: hype or revolution?", options: ["Revolution", "Hype", "Both"], tags: ["tech", "hot-take"] },
  { id: "q118", prompt: "Best browser?", options: ["Chrome", "Firefox", "Arc", "Safari"], tags: ["tech"] },
  { id: "q119", prompt: "Most overrated tech product?", options: ["Apple Vision Pro", "Tesla", "Crypto", "Smart fridge"], tags: ["tech", "hot-take"] },
  { id: "q120", prompt: "Crypto: legit or scam?", options: ["Legit", "Scam", "Mostly scam"], tags: ["tech", "hot-take"] },
  { id: "q121", prompt: "Best streaming service?", options: ["Netflix", "Max", "Disney+", "Apple TV+"], tags: ["tech"] },
  { id: "q122", prompt: "Tabs or spaces?", options: ["Tabs", "Spaces", "I just want them to work"], tags: ["tech", "hot-take"] },
  { id: "q123", prompt: "Worst CEO of the last 10 years?", options: ["Elon", "Zuckerberg", "Bezos", "Bobby Kotick"], tags: ["tech", "dark-humor"] },

  // ===== INTERNET =====
  { id: "q124", prompt: "Best meme format of all time?", options: ["Distracted boyfriend", "Drake Yes/No", "Doge", "This is fine"], tags: ["internet"] },
  { id: "q125", prompt: "TikTok or Instagram Reels?", options: ["TikTok", "Reels", "Neither", "Both equally bad"], tags: ["internet", "hot-take"] },
  { id: "q126", prompt: "Most chronically online behavior?", options: ["Posting your meal", "Replying 'literally me' to strangers", "Twitter discourse", "Hot take threads"], tags: ["internet", "dark-humor"] },
  { id: "q127", prompt: "Best YouTuber ever?", options: ["MrBeast", "Mark Rober", "Tom Scott", "Markiplier"], tags: ["internet", "hot-take"] },
  { id: "q128", prompt: "Worst content trend?", options: ["Reaction videos", "Day-in-my-life", "Mukbangs", "Prank channels"], tags: ["internet"] },
  { id: "q129", prompt: "Twitter (X) opinion?", options: ["Worse than before", "About the same", "Actually better"], tags: ["internet", "hot-take"] },
  { id: "q130", prompt: "Posting or lurking?", options: ["Posting", "Lurking", "Lurk-post (mostly lurk)"], tags: ["internet"] },
  { id: "q131", prompt: "Best old internet site you miss?", options: ["Vine", "Tumblr (peak)", "Old YouTube", "MySpace"], tags: ["internet", "nostalgia"] },
  { id: "q132", prompt: "Reddit: net positive or negative?", options: ["Positive", "Negative", "Neutral"], tags: ["internet", "hot-take"] },
  { id: "q133", prompt: "Worst comment section?", options: ["YouTube", "TikTok", "Twitter replies", "Local news Facebook"], tags: ["internet", "dark-humor"] },
  { id: "q134", prompt: "Best cursed image energy?", options: ["Liminal spaces", "Backrooms", "Weird Wikipedia", "Old family photos"], tags: ["internet", "weird"] },
  { id: "q135", prompt: "Most overrated podcast?", options: ["Joe Rogan", "Call Her Daddy", "Smartless", "This American Life"], tags: ["internet", "hot-take"] },

  // ===== SCHOOL / NOSTALGIA =====
  { id: "q136", prompt: "Best year of school?", options: ["Elementary", "Middle school", "High school", "College"], tags: ["school", "nostalgia"] },
  { id: "q137", prompt: "Best recess game?", options: ["Four square", "Wall ball", "Tag", "Kickball"], tags: ["school", "nostalgia"] },
  { id: "q138", prompt: "Best school subject?", options: ["Math", "English", "Science", "Art"], tags: ["school", "hot-take"] },
  { id: "q139", prompt: "Worst school subject?", options: ["Math", "PE", "History", "Foreign language"], tags: ["school", "hot-take"] },
  { id: "q140", prompt: "Best school lunch food?", options: ["Pizza Friday", "Chicken nuggets", "Mac and cheese", "Cookies"], tags: ["school", "nostalgia"] },
  { id: "q141", prompt: "Snow day or sick day?", options: ["Snow day", "Sick day", "Neither, give me class"], tags: ["school", "wholesome"] },
  { id: "q142", prompt: "Best field trip?", options: ["Zoo", "Museum", "Science center", "Amusement park"], tags: ["school", "nostalgia"] },
  { id: "q143", prompt: "Hardest grade of school?", options: ["7th grade", "10th grade", "Senior year", "College sophomore"], tags: ["school", "hot-take"] },
  { id: "q144", prompt: "Best childhood show?", options: ["Spongebob", "Avatar TLA", "Phineas and Ferb", "Hey Arnold"], tags: ["nostalgia", "wholesome"] },
  { id: "q145", prompt: "Best childhood toy?", options: ["LEGO", "Hot Wheels", "Beyblade", "Bionicles"], tags: ["nostalgia"] },
  { id: "q146", prompt: "Best Disney Channel show?", options: ["Wizards of Waverly Place", "Hannah Montana", "Suite Life", "That's So Raven"], tags: ["nostalgia"] },
  { id: "q147", prompt: "Best Nickelodeon show?", options: ["Spongebob", "Avatar", "Drake & Josh", "iCarly"], tags: ["nostalgia", "hot-take"] },
  { id: "q148", prompt: "Best cereal of your childhood?", options: ["Cinnamon Toast Crunch", "Lucky Charms", "Frosted Flakes", "Cookie Crisp"], tags: ["nostalgia", "food"] },
  { id: "q149", prompt: "Most nostalgic smell?", options: ["Crayons", "Playdough", "Old books", "Fresh-cut grass"], tags: ["nostalgia", "wholesome"] },
  { id: "q150", prompt: "Best 2000s/2010s teen movie?", options: ["Mean Girls", "Superbad", "Easy A", "10 Things I Hate About You"], tags: ["nostalgia", "movies"] },

  // ===== FRIENDSHIP / WHOLESOME =====
  { id: "q151", prompt: "Best activity for a first hangout?", options: ["Get food", "Coffee", "Walk", "Game night"], tags: ["friendship", "wholesome"] },
  { id: "q152", prompt: "Group dinner vibe?", options: ["Sit-down restaurant", "Potluck", "Takeout at someone's place", "Cooking together"], tags: ["friendship", "food"] },
  { id: "q153", prompt: "Best gift to receive?", options: ["Experience", "Something handmade", "Cash", "A book they picked"], tags: ["friendship", "wholesome"] },
  { id: "q154", prompt: "Best way to spend a Friday night?", options: ["Going out", "Game night with friends", "Movie at home", "Just sleep"], tags: ["friendship"] },
  { id: "q155", prompt: "Best road trip activity?", options: ["AUX battle", "Podcast", "Snacks debate", "Singing along"], tags: ["friendship", "wholesome"] },
  { id: "q156", prompt: "Best birthday plan?", options: ["Big party", "Small dinner with close friends", "Just me and one person", "Skip it"], tags: ["friendship", "wholesome"] },
  { id: "q157", prompt: "Best way to start a long friendship?", options: ["School/work proximity", "Shared interest", "Mutual friend", "Random encounter"], tags: ["friendship", "wholesome"] },
  { id: "q158", prompt: "Worst friend behavior?", options: ["Always late", "Cancels last-minute", "Bad at texting back", "Steals your fries"], tags: ["friendship", "hot-take"] },
  { id: "q159", prompt: "Best place to live forever?", options: ["NYC", "Tokyo", "London", "Small mountain town"], tags: ["friendship", "hypothetical"] },
  { id: "q160", prompt: "Best concert with friends?", options: ["Festival", "Stadium show", "Small venue", "House show"], tags: ["friendship", "music"] },

  // ===== HYPOTHETICAL / WOULD YOU RATHER =====
  { id: "q161", prompt: "Fly or be invisible?", options: ["Fly", "Invisible", "Neither thanks"], tags: ["hypothetical"] },
  { id: "q162", prompt: "Read minds or time travel?", options: ["Read minds", "Time travel", "Honestly neither"], tags: ["hypothetical"] },
  { id: "q163", prompt: "One meal for the rest of your life?", options: ["Pizza", "Sushi", "Tacos", "Pasta"], tags: ["hypothetical", "food"] },
  { id: "q164", prompt: "One song on repeat forever?", options: ["Mr. Brightside", "Africa", "Don't Stop Believin'", "Wonderwall"], tags: ["hypothetical", "music"] },
  { id: "q165", prompt: "Lose your phone or your wallet?", options: ["Phone", "Wallet", "Both equally awful"], tags: ["hypothetical"] },
  { id: "q166", prompt: "Be famous or be rich?", options: ["Rich", "Famous", "Both", "Neither"], tags: ["hypothetical"] },
  { id: "q167", prompt: "Live in the past or the future?", options: ["Past", "Future", "Present is fine"], tags: ["hypothetical"] },
  { id: "q168", prompt: "Best decade to live in?", options: ["80s", "90s", "2000s", "Right now"], tags: ["hypothetical", "nostalgia"] },
  { id: "q169", prompt: "Trade lives with whom?", options: ["A celebrity", "A historical figure", "A random stranger", "No one"], tags: ["hypothetical"] },
  { id: "q170", prompt: "Best superpower for daily life?", options: ["Teleportation", "Stop time", "Talk to animals", "Speak any language"], tags: ["hypothetical"] },
  { id: "q171", prompt: "Sleep talk or sleepwalk?", options: ["Sleep talk", "Sleepwalk", "Neither"], tags: ["hypothetical", "weird"] },
  { id: "q172", prompt: "Best alarm clock sound?", options: ["Birds", "Radio", "Old-school beep", "Silence + sunlight"], tags: ["hypothetical", "wholesome"] },
  { id: "q173", prompt: "Win the lottery: what's first?", options: ["Pay debts", "Buy a house", "Travel", "Quit job immediately"], tags: ["hypothetical"] },
  { id: "q174", prompt: "Stuck on a desert island with one person?", options: ["Survival expert", "Best friend", "Your favorite celeb", "Solo gang"], tags: ["hypothetical", "friendship"] },
  { id: "q175", prompt: "Be 5 years older or 5 years younger forever?", options: ["Older", "Younger", "Current age"], tags: ["hypothetical"] },

  // ===== WEIRD / DARK HUMOR =====
  { id: "q176", prompt: "Weirdest thing you'd eat for $1000?", options: ["A bug", "A whole raw onion", "A spoonful of mayo", "10 ghost peppers"], tags: ["weird", "dark-humor", "food"] },
  { id: "q177", prompt: "Most haunted object in your house?", options: ["Old mirror", "Family photo", "Doll", "That one drawer"], tags: ["weird", "dark-humor"] },
  { id: "q178", prompt: "Most unsettling sound?", options: ["Nails on chalkboard", "Polystyrene squeak", "Children laughing in distance", "Phone vibrating in empty room"], tags: ["weird"] },
  { id: "q179", prompt: "Worst hill to die on?", options: ["Pineapple on pizza", "Cereal milk first", "Hot dog is a sandwich", "Toilet paper over vs under"], tags: ["weird", "hot-take"] },
  { id: "q180", prompt: "Strangest dream you've had recently?", options: ["Lost in a familiar place", "Teeth falling out", "Late for something", "Flying"], tags: ["weird"] },
  { id: "q181", prompt: "Worst way to wake up?", options: ["Sibling jumping on you", "Phone alarm at 1% battery", "Dog licking your face", "Cold water"], tags: ["weird", "dark-humor"] },
  { id: "q182", prompt: "Most cursed sandwich?", options: ["Pickles + Nutella", "Banana + mayo", "Cold spaghetti", "Plain white bread + ketchup"], tags: ["weird", "food"] },
  { id: "q183", prompt: "What body part do you wish you had two of?", options: ["Brain", "Stomach", "Arms", "Eyes (in back of head)"], tags: ["weird", "hypothetical"] },
  { id: "q184", prompt: "Worst place to be ghosted?", options: ["Mid-text", "After a first date", "On a group project", "Right before plans"], tags: ["dark-humor", "friendship"] },
  { id: "q185", prompt: "Most universally annoying noise?", options: ["Slurping", "Loud chewing", "Phone speakerphone in public", "Knuckle cracking"], tags: ["weird", "hot-take"] },

  // ===== MIXED / EXTRAS =====
  { id: "q186", prompt: "Best app on your phone right now?", options: ["Spotify", "Notes", "Maps", "Camera"], tags: ["tech"] },
  { id: "q187", prompt: "Best wedding song?", options: ["September", "I Wanna Dance With Somebody", "Mr. Brightside", "Y.M.C.A."], tags: ["music", "wholesome"] },
  { id: "q188", prompt: "Most useless skill you have?", options: ["Memorizing song lyrics", "Whistling", "Tying knots", "Random history facts"], tags: ["friendship", "wholesome"] },
  { id: "q189", prompt: "Best season?", options: ["Spring", "Summer", "Fall", "Winter"], tags: ["wholesome", "hot-take"] },
  { id: "q190", prompt: "Best holiday?", options: ["Christmas", "Thanksgiving", "Halloween", "4th of July"], tags: ["nostalgia", "wholesome"] },
  { id: "q191", prompt: "Best convenience store snack?", options: ["Slurpee", "Hot Cheetos", "Beef jerky", "Reese's"], tags: ["food", "nostalgia"] },
  { id: "q192", prompt: "Best Halloween candy?", options: ["Reese's", "Kit Kat", "Snickers", "Twix"], tags: ["food", "nostalgia"] },
  { id: "q193", prompt: "Worst Halloween candy?", options: ["Candy corn", "Tootsie Rolls", "Black licorice", "Raisins"], tags: ["food", "hot-take"] },
  { id: "q194", prompt: "Best NBA franchise of the last 25 years?", options: ["Lakers", "Warriors", "Spurs", "Heat"], tags: ["sports", "hot-take"] },
  { id: "q195", prompt: "Most underrated MCU character?", options: ["Vision", "Yelena Belova", "Loki", "Wong"], tags: ["movies"] },
  { id: "q196", prompt: "Best Disney villain?", options: ["Scar", "Maleficent", "Ursula", "Jafar"], tags: ["movies", "nostalgia"] },
  { id: "q197", prompt: "Best dance from the 2010s?", options: ["The Dougie", "Whip/Nae Nae", "Gangnam Style", "Harlem Shake"], tags: ["nostalgia", "music"] },
  { id: "q198", prompt: "Show you binged way too fast?", options: ["Stranger Things", "Squid Game", "Wednesday", "The Bear"], tags: ["movies"] },
  { id: "q199", prompt: "Worst movie ending?", options: ["Game of Thrones (close enough)", "How I Met Your Mother", "Lost", "Dexter"], tags: ["movies", "hot-take"] },
  { id: "q200", prompt: "Best modern animated show?", options: ["Arcane", "Bluey", "Spider-Verse vibes", "Invincible"], tags: ["movies", "anime"] },
  { id: "q201", prompt: "Best place to nap?", options: ["Couch", "Bed", "Car passenger seat", "Floor (real ones know)"], tags: ["weird", "wholesome"] },
  { id: "q202", prompt: "Most underrated body part?", options: ["Elbows", "Earlobes", "Pinky toe", "Knees"], tags: ["weird"] },
  { id: "q203", prompt: "Most embarrassing fear?", options: ["Mascots", "Clowns", "Dolls", "Butterflies"], tags: ["weird", "dark-humor"] },
  { id: "q204", prompt: "Best gas station food?", options: ["Buc-ee's anything", "Wawa hoagie", "Sheetz MTO", "7-Eleven taquito"], tags: ["food"] },
  { id: "q205", prompt: "Most universally loved sound?", options: ["Rain on a window", "Coffee brewing", "Cat purring", "Fireplace crackling"], tags: ["wholesome"] },
  { id: "q206", prompt: "Best small joy?", options: ["Hot shower", "Clean sheets", "First sip of coffee", "Phone at 100%"], tags: ["wholesome"] },
  { id: "q207", prompt: "What's universally overrated?", options: ["Brunch", "Coachella", "Beach vacations", "Wedding rituals"], tags: ["hot-take"] },
  { id: "q208", prompt: "What's universally underrated?", options: ["Going to bed early", "Long walks", "Library hangouts", "Cooking at home"], tags: ["wholesome", "hot-take"] },
  { id: "q209", prompt: "Best emoji?", options: ["💀", "😭", "🙏", "🥲"], tags: ["internet"] },
  { id: "q210", prompt: "Worst overused emoji?", options: ["😂", "👍", "✨", "🥹"], tags: ["internet", "hot-take"] },
];
